version: "3.9"

services:

  reverseproxy:
    build:
      context: ./Nginx
      dockerfile: Nginx.Dockerfile
    ports:
      - "4000:4000"
    restart: always

  api:
    depends_on:
      - reverseproxy
    build:
      dockerfile: Api.Dockerfile
    expose:
      - "5000"
    restart: always