name: Docker

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set Repository Name to Lowercase
        run: |
            echo "REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${REPOSITORY}
  
      - name: Build the Docker Images
        run: export DOCKER_REGISTRY=${{ env.REGISTRY }}/${REPOSITORY}/ && export TAG=${{ github.ref_name }} && docker-compose build
      
      - name: Push to ${{ env.REGISTRY }} Registry
        run: export DOCKER_REGISTRY=${{ env.REGISTRY }}/${REPOSITORY}/ && export TAG=${{ github.ref_name }} && docker-compose push